(define-library (lassik tex-parser)
  (export read-tex-document)
  (import (scheme base)
          (scheme char)
          (scheme file)
          (lassik read-char-if))
  (include "tex-parser.scm"))
